# https://github.com/probot/settings

# https://docs.github.com/en/rest/reference/issues#create-a-label
# https://docs.github.com/en/rest/reference/issues#update-a-label

labels:
  - name: "bug"
    color: "ee0701"
    description: ""

  - name: "dependency"
    color: "0366d6"
    description: ""

  - name: "enhancement"
    color: "0e8a16"
    description: ""

  - name: "merge"
    color: "6f42c1"
    description: ""

  - name: "question"
    color: "cc317c"
    description: ""

  - name: "security"
    color: "ee0701"
    description: ""

  - name: "stale"
    color: "eeeeee"
    description: ""

# https://docs.github.com/en/rest/reference/repos#update-a-repository

repository:
  allow_merge_commit: true
  allow_rebase_merge: false
  allow_squash_merge: false
  archived: false
  default_branch: "main"
  delete_branch_on_merge: true
  description: ":wave: Provides a README.md for @localheinz."
  has_downloads: false
  has_issues: false
  has_pages: false
  has_projects: false
  has_wiki: false
  name: "localheinz"
  private: false

  # https://docs.github.com/en/rest/reference/repos#replace-all-repository-topics

  topics: "personal, readme"
