# https://docs.github.com/en/actions

name: "Integrate"

on: # yamllint disable-line rule:truthy
  pull_request: null
  push:
    branches:
      - "main"

env:
  ERGEBNIS_BOT_NAME: "ergebnis-bot"

jobs:
  coding-standards:
    name: "Coding Standards"

    runs-on: "ubuntu-latest"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v3.0.2"

      - name: "Lint YAML files"
        uses: "ibiqlik/action-yamllint@v3"
        with:
          config_file: ".yamllint.yaml"
          file_or_dir: "."
          strict: true
