# https://docs.github.com/en/actions

name: "Update"

on: # yamllint disable-line rule:truthy
  push:
    branches:
      - "main"
  schedule:
    - cron: "0 */1 * * *"

jobs:
  readme:
    name: "Readme"

    runs-on: "ubuntu-latest"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4.1.3"
        with:
          token: "${{ secrets.ERGEBNIS_BOT_TOKEN }}"

      - name: "Regenerate README.md"
        uses: "muesli/readme-scribe@v0.1"
        env:
          GITHUB_TOKEN: "${{ secrets.LOCALHEINZ_TOKEN }}"
        with:
          template: "template/README.md.tpl"
          writeTo: "README.md"

      - name: "Commit README.md"
        uses: "stefanzweifel/git-auto-commit-action@v5.0.0"
        with:
          commit_author: "ergebnis-bot <bot@ergebn.is>"
          commit_message: "Enhancement: Update README.md"
          commit_user_email: "bot@ergebn.is"
          commit_user_name: "ergebnis-bot"
